# Generated by Django 3.2 on 2024-04-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
        ('profiles', '0001_initial'),
        ('wishlist', '0002_alter_wishlist_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to='profiles.userprofile'),
        ),
    ]
