# Generated by Django 3.2 on 2024-04-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20240417_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
