# Generated by Django 3.2 on 2024-04-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20240418_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
